name: ItemFrameUtils
version: ${project.version}
main: uk.co.voxelfox.itemframeutils.ItemFrameUtils
api-version: 1.16

commands:
  setframevisible:
    usage: '/setframevisible <true/false> [distance] [limit?]'
    description: 'Set nearby item frames to either invisible or visible'
